### ISSUE TITLE
Cannot remove "babel-plugin-transform-es2015-modules-commonjs" 

### ISSUE THREAD

**Issue by hq5544** [vuejs-templates/webpack-simple-2.0#11]
When I run the `dev` script, it says:

```
ERROR in ./src/main.js
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/Users/hq5544/Documents/vue/vue-cli-2/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/hq5544/Documents/vue/vue-cli-2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
 @ multi main
```

I didn't change anything.

**Comment by cheft** [comment]
+1

**Comment by cheft** [comment]
试了两种方案，暂时可行：
* 修改 `.babelrc `文件，改为：`"presets": []`
* 修改 `node_modules/babel-preset-es2015-webpack/index.js` 文件

      if (es2015PluginList.length !== es2015WebpackPluginList.length + 1) {

    改为

      if (es2015PluginList.length !== es2015WebpackPluginList.length) {

**Comment by hq5544** [comment]
@cheft It works. Thanks!
