### ISSUE TITLE
Couldn't find preset "stage-2"

### ISSUE THREAD

**Issue by cnweibo** [vuejs-templates/webpack-simple-2.0#14]
when i do according to document, run: npm run dev, following error happens:
```
$ npm run dev

> vue2.0@ dev C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp
> webpack-dev-server --inline --hot

 http://localhost:8080/
webpack result is served from /dist/
content is served from C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp
404s will fallback to /index.html
Hash: 24eaffa905d8774eaf09
Version: webpack 2.1.0-beta.20
Time: 8647ms
   Asset    Size  Chunks             Chunk Names
build.js  689 kB       0  [emitted]  main
chunk    {0} build.js (main) 231 kB [entry] [rendered]
    [0] (webpack)-dev-server/~/sockjs-client/~/inherits/inherits_browser.js 672 bytes {0} [built]
    [1] (webpack)/buildin/global.js 506 bytes {0} [built]
    [2] (webpack)-dev-server/~/sockjs-client/~/debug/browser.js 3.76 kB {0} [built]
    [3] (webpack)/~/node-libs-browser/~/process/browser.js 3.21 kB {0} [built]
    [4] (webpack)-dev-server/~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
    [5] (webpack)-dev-server/~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
    [6] (webpack)-dev-server/~/sockjs-client/~/json3/lib/json3.js 43.3 kB {0} [built]
    [7] (webpack)-dev-server/~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
    [8] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
    [9] (webpack)-dev-server/~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [10] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [11] (webpack)-dev-server/~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [12] (webpack)-dev-server/~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [13] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [14] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [15] (webpack)-dev-server/~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [16] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [17] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [18] (webpack)-dev-server/~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [19] (webpack)-dev-server/~/sockjs-client/~/url-parse/index.js 8.09 kB {0} [built]
   [20] (webpack)-dev-server/~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [21] (webpack)-dev-server/~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [22] (webpack)-dev-server/~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [23] (webpack)-dev-server/~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [24] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [25] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [26] (webpack)-dev-server/~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [27] (webpack)-dev-server/~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [28] (webpack)-dev-server/~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [29] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [30] (webpack)-dev-server/~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [31] (webpack)-dev-server/~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [32] (webpack)-dev-server/~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [33] (webpack)/buildin/module.js 548 bytes {0} [built]
   [34] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [35] ./src/main.js 2.09 kB {0} [built] [failed] [1 error]
   [36] (webpack)-dev-server/client?http://localhost:8080 3.12 kB {0} [built]
   [37] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
   [38] (webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [39] (webpack)-dev-server/~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [40] (webpack)-dev-server/~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [41] (webpack)-dev-server/~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [42] (webpack)-dev-server/~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [43] (webpack)-dev-server/~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [44] (webpack)-dev-server/~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [45] (webpack)-dev-server/~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [46] (webpack)-dev-server/~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [47] (webpack)-dev-server/~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [48] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0} [built]
   [49] (webpack)-dev-server/~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [50] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [51] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [52] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [53] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [54] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [55] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [56] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [57] (webpack)-dev-server/~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [58] (webpack)-dev-server/~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [59] (webpack)-dev-server/~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [60] (webpack)-dev-server/~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [61] (webpack)-dev-server/~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [62] (webpack)-dev-server/~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [63] (webpack)-dev-server/~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [64] (webpack)-dev-server/~/sockjs-client/~/debug/debug.js 4.1 kB {0} [built]
   [65] (webpack)-dev-server/~/sockjs-client/~/debug/~/ms/index.js 2.33 kB {0} [built]
   [66] (webpack)-dev-server/~/sockjs-client/~/url-parse/lolcation.js 1.58 kB {0} [built]
   [67] (webpack)-dev-server/~/sockjs-client/~/url-parse/~/querystringify/index.js 1.3 kB {0} [built]
   [68] (webpack)-dev-server/~/sockjs-client/~/url-parse/~/requires-port/index.js 753 bytes {0} [built]
   [69] (webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [70] (webpack)-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes {0} [built]
   [71] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [72] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
   [73] (webpack)/~/node-libs-browser/~/events/events.js 8.33 kB {0} [built]
   [74] (webpack)/~/node-libs-browser/~/punycode/punycode.js 14.7 kB {0} [built]
   [75] (webpack)/~/node-libs-browser/~/querystring-es3/decode.js 2.51 kB {0} [built]
   [76] (webpack)/~/node-libs-browser/~/querystring-es3/encode.js 2.54 kB {0} [built]
   [77] (webpack)/~/node-libs-browser/~/querystring-es3/index.js 127 bytes {0} [built]
   [78] (webpack)/~/node-libs-browser/~/url/url.js 23.3 kB {0} [built]
   [79] (webpack)/~/node-libs-browser/~/url/util.js 314 bytes {0} [built]
   [80] multi main 52 bytes {0} [built]

ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "stage-2" relative to directory "C:\\Users\\Administrator\\devenvironment\\Code\\resources\\assets\\js\\vueapp"
    at C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:321:17
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:305:20)
    at OptionManager.mergePresets (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:288:10)
    at OptionManager.mergeOptions (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:14)
    at OptionManager.init (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:383:12)
    at File.initOptions (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\index.js:223:65)
    at new File (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\file\index.js:140:24)
    at Pipeline.transform (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\devenvironment\Code\resources\assets\js\vueapp\node_modules\babel-loader\index.js:14:22)
 @ multi main
 Couldn't find preset "stage-2"

```

**Comment by cnweibo** [comment]
My solution was :
``` 
npm install --save-dev babel-preset-stage-2
```
I do not know whether or not my solution is good. Or vuejs-template should update the package.json including it.

**Comment by yyx990803** [comment]
The template's `.babelrc` doesn't use `stage-2`. This is probably your babel config problem.
